name: dele-github-branches

on:
  pull_request:
  # At 00:00 everyday
  schedule:
    - cron: '0 0 * * *'

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Setup Node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node_version }}
      - name: Run delete-github-branches
        run: |
          npx delete-github-branches --config ./.github/delete-github-branches.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-pull-request-branch:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Setup Node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node_version }}
      - name: Check branch name
        run: |
          export GITHUB_BRANCH=${GITHUB_REF##*heads/}
          export OUTPUT_CHECK_BRANCH=$(npx -p delete-github-branches delete-github-branches-check-branch-name --config ./.github/delete-github-branches.json "${GITHUB_BRANCH}")
          echo "::set-env name=OUTPUT_CHECK_BRANCH::${OUTPUT_CHECK_BRANCH}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-pull-request-branch-fail-comment:
    if: failure()
    needs: check-pull-request-branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: comment "@${{ github.actor }} ${OUTPUT_CHECK_BRANCH}"
